### ISSUE TITLE
add s3 backend for blob storage

### ISSUE THREAD

**Issue by darkskygit** [toeverything/OctoBase#374]
```[tasklist]
### Tasks
- [ ] https://github.com/toeverything/OctoBase/issues/463
- [ ] https://github.com/toeverything/OctoBase/issues/464
- [ ] https://github.com/toeverything/OctoBase/issues/465
```

init PR：https://github.com/toeverything/OctoBase/pull/466

**Comment by tzhangchi** [comment]
Is it supported that @Himself65   will be responsible for the future

**Comment by Xuanwo** [comment]
Hello, have you heard of [opendal](https://github.com/apache/incubator-opendal)? It is an Apache incubator project that enables users to access data freely. We support various storage backends such as s3, gcs, azblob and webdav. Do you think it would be a good fit for your needs?

P.S: I'm the maintainer of this project.

**Comment by Himself65** [comment]
> Hello, have you heard of [opendal](https://github.com/apache/incubator-opendal)? It is an Apache incubator project that enables users to access data freely. We support various storage backends such as s3, gcs, azblob and webdav. Do you think it would be a good fit for your needs?
> 
> P.S: I'm the maintainer of this project.

Thanks for the suggestion. I read the document, but we want to have a node.js backend for the storage API

**Comment by darkskygit** [comment]
> Hello, have you heard of [opendal](https://github.com/apache/incubator-opendal)? It is an Apache incubator project that enables users to access data freely. We support various storage backends such as s3, gcs, azblob and webdav. Do you think it would be a good fit for your needs?
> 
> P.S: I'm the maintainer of this project.

I think this library is very suitable for our storage layer design principles, we will discuss the possibility of intervening in the storage layer

**Comment by darkskygit** [comment]
> Hi! Is there any progress on this issue? We are planning to use octobase as our collaboration server but storing blob in database might be too expensive especially our workflow involves a lot of images.

Thank you for your interest! We just discussed the progress of this issue today, and currently we plan to provide support for s3 and more storage layers based on [opendal](https://github.com/apache/incubator-opendal)

**Comment by Xuanwo** [comment]
Wow, I'm also interested in taking part!

**Comment by thorseraq** [comment]
Hi, @Xuanwo, We currently have three subtasks open related to this issue, you're welcome to pick any of these subtasks that you feel comfortable with~ 

There might be more subtasks added later, such as unit test, use [incubator-opendal](https://github.com/apache/incubator-opendal) middleware layers and so on

**Comment by thorseraq** [comment]
Following ongoing tasks are tracked here before starting:

- [ ] #463 (not started)
- [ ] #464 (not started)
- [ ] #465 (not started)
