### ISSUE TITLE
webrtc connector

### ISSUE THREAD

**Issue by darkskygit** [toeverything/OctoBase#431]
we plan to implement a connector based on WebRTC, which will help web version users connect to their octobase server in a peer-to-peer manner without needing to go through a central server for relay.

```[tasklist]
### Tasks
- [x] webrtc handshake helper / webrtc signalling server #446
- [x] webrtc connector (tx/rx thread) #444
- [x] unit test for webrtc connector #444
```

Refs:
- https://github.com/toeverything/OctoBase/issues/287
- https://octobase.pro/docs/implementation/connector

**Comment by a-wing** [comment]
I'm trying to implement it using [webrtc-rs](https://github.com/webrtc-rs/webrtc)

I'm going to implement a very simple scenario first: local-to-local

For signalling server, There is no need for a cloud server, use a local client-server exchange for signalling (Maybe in future, need a local discovery)

Only peer-c and peer-s:
1. peer-s as a server, has a HTTP API, maybe `/webrtc-sdp`
2. peer-c as a client, HTTP-POST peer-s `/webrtc-sdp` (webrtc-signal: peer-c offer send)
3. peer-s worker respose peer-c (webrtc-signal: peer-s recevier offer, and create answer)
4. peer-c and peer-s use webrtc-datachannel connected as peer-to-peer (webrtc-signal: peer-c recevier answer, start peer-to-peer connect)

OctoBase and OctoBase can connected without relay in the local

How about do you think?

**Comment by darkskygit** [comment]
> I'm trying to implement it using [webrtc-rs](https://github.com/webrtc-rs/webrtc)
> 
> I'm going to implement a very simple scenario first: local-to-local
> 
> For signalling server, There is no need for a cloud server, use a local client-server exchange for signalling (Maybe in future, need a local discovery)
> 
> Only peer-c and peer-s:
> 
> 1. peer-s as a server, has a HTTP API, maybe `/webrtc-sdp`
> 2. peer-c as a client, HTTP-POST peer-s `/webrtc-sdp` (webrtc-signal: peer-c offer send)
> 3. peer-s worker respose peer-c (webrtc-signal: peer-s recevier offer, and create answer)
> 4. peer-c and peer-s use webrtc-datachannel connected as peer-to-peer (webrtc-signal: peer-c recevier answer, start peer-to-peer connect)
> 
> OctoBase and OctoBase can connected without relay in the local
> 
> How about do you think?

sounds good!

**Comment by darkskygit** [comment]
finished at #444 #446
