### ISSUE TITLE
house keeping: code robustness

### ISSUE THREAD

**Issue by darkskygit** [toeverything/OctoBase#479]
```[tasklist]
### Tasks
- [x] use [AddressSanitizer](https://github.com/google/sanitizers/wiki/AddressSanitizer) check memory error in ci #481
- [x] add memory leak check fuzzing & test(#481) in ci
- [x] add miri check ffi / unsafe codes in ci
- [x] fix memory leak in codec #478
- [x] use [loom](https://github.com/tokio-rs/loom) detect unsound multi-thread behavior #485
```

**Comment by darkskygit** [comment]
all tasks finished
