### ISSUE TITLE
🔥 Roadmap for OctoBase pre-alpha

### ISSUE THREAD

**Issue by tzhangchi** [toeverything/OctoBase#9]
## JWSTBase

 - Final tasks has been move to hidden comment
     - [10/13](https://github.com/toeverything/JWST/issues/9#issuecomment-1277217012)

### workspace

  - [x] block index @darkskygit 
  - [ ] cross-docs block or docs relink @darkskygit 
      - we can link another docs as a block children, but did we need to hidden this detial as subdoc abstract?
      - when we link doc as a subdoc, how we build the cross-doc block graph?
  - [ ] sync block to another workspace @darkskygit 

### block

  - [ ] block children instance(exists/get) @darkskygit 
  - [ ] block parent mapping @darkskygit @Austaras 
  - [ ] block events @Austaras 
  - [x] #30

### Cross Platform

 - [x] #32
 - [ ] cffi unit test @Austaras 
 - [ ] #31

### Storage

- [x] SQLite / MySQL feature
- [x] stand-alone crate

## Keck

* [ ] Unit test for server side api @darkskygit  @MIracleyin qian

## Document

* [ ] How to create a basic project with jwst
* [ ] How to organizing data using the Block abstraction

### plugin

  - [ ] dynamic plugin research: how we create the plugin solution with rust? @darkskygit 
      - at this time we impl plugin as a feature included jwst library
      - [ ] plugin api design @darkskygit @Austaras 
      - [ ] indexer integrate @darkskygit
